<?php

namespace FormHandler;
use \FormHandler\Utils;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-28 at 11:07:30.
 */
class UtilsTest extends \PHPUnit_Framework_TestCase
{
    public function testHtml()
    {
        $list = array(
            'https://test.com/' => 'https://test.com/',
            'https://test.com/<script>' => 'https://test.com/&lt;script&gt;',
            'https://test.com/<script>alert(\'1\')</script>' => 'https://test.com/&lt;script&gt;alert(&#039;1&#039;)&lt;/script&gt;',
            'https://test.com/<script>alert("1")</script>' => 'https://test.com/&lt;script&gt;alert(&quot;1&quot;)&lt;/script&gt;',
            'https://test.com/test.php?">' => 'https://test.com/test.php?&quot;&gt;',
        );

        foreach($list as $input => $check)
        {
            $this->assertEquals(Utils::html($input), $check);
        }
    }
}
